name = "DynamicalCorrelators"
uuid = "7abe38c7-550a-49b0-ba99-33d1b5164ede"
authors = ["Y.-Y.Zong"]
version = "0.5.3"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPSKit = "bb1c41ca-d63c-52ed-829e-0820dda26502"
MPSKitModels = "ca635005-6f8c-4cd1-b51d-8491250ef2ab"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuantumLattices = "78ae1a1f-1d5d-5174-b61c-66e31b2346dc"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
Dates = "1.11"
JLD2 = "0.5"
KrylovKit = "0.9, 0.10"
MPSKit = "0.13"
MPSKitModels = "0.4"
NumericalIntegration = "0.3"
Printf = "1.11"
QuantumLattices = "0.11, 0.12, 0.13"
TensorKit = "0.14"
TensorOperations = "5.3"
julia = "1.11"
